name: Sync with upstream fork on bitbucket

env:
  UPSTREAM_URL: "https://bitbucket.org/atagunov/metayaml.git"
  WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UPSTREAM_BRANCH: "master"
  DOWNSTREAM_BRANCH: "sync-attempt-${{ github.run_id }}-${{ github.run_attempt }}"
  FETCH_ARGS: "--allow-unrelated-histories"
  MERGE_ARGS: ""
  PUSH_ARGS: ""
  SPAWN_LOGS: "false"

on:
#   schedule:
#     - cron: 0 13 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
          fetch_args: ${{ env.FETCH_ARGS }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}
          spawn_logs: ${{ env.SPAWN_LOGS }}

      - uses: technote-space/get-diff-action@v6

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        env:
          branch: ${{ env.DOWNSTREAM_BRANCH }}
          base: main
        if: env.GIT_DIFF
